version: 2
jobs:
  build_pytest:
    machine:
      image: default
    working_directory: /tmp/src/nitransforms
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      FS_LICENSE: "/tmp/fslicense/license.txt"

    steps:
      - checkout
      - restore_cache:
          keys:
            - env-v6-{{ .Branch }}-
            - env-v6-master-
            - env-v6-
      - run:
          name: Setup git-annex
          command: |
              sudo apt update && sudo apt-get install apt-transport-https ca-certificates -y && sudo update-ca-certificates
              if [[ ! -d /opt/circleci/git-annex.linux ]]; then
                cd /tmp
                wget https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz
                tar xzf git-annex-standalone-amd64.tar.gz -C /opt/circleci/
              fi
              git config --global user.name 'NiPy'
              git config --global user.email 'nipreps@gmail.com'
      - run:
          name: Setup DataLad
          command: |
              python3 -m pip install --no-cache-dir -U pip "setuptools >= 45.0" "setuptools_scm[toml] >= 6.2"
              python3 -m pip install --no-cache-dir -U datalad datalad-osf

      - save_cache:
          key: env-v6-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - /opt/circleci/git-annex.linux
            - /opt/circleci/.pyenv/versions

      - restore_cache:
          keys:
            - data-v3-{{ .Branch }}-
            - data-v3-master-
            - data-v3-
      - run:
          name: Install test data from GIN
          command: |
              export PATH=/opt/circleci/git-annex.linux:$PATH
              pyenv local 3
              eval "$(pyenv init --path)"
              mkdir -p /tmp/data
              cd /tmp/data
              datalad install -r https://gin.g-node.org/oesteban/nitransforms-tests
              datalad update --merge -d ./nitransforms-tests/
              datalad get -r -d ./nitransforms-tests/ *
      - save_cache:
          key: data-v3-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - /tmp/data

      - restore_cache:
          keys:
            - build-v1-{{ .Branch }}-{{ epoch }}
            - build-v1-{{ .Branch }}-
            - build-v1-master-
            - build-v1-
          paths:
            - /tmp/docker
      - run:
          name: Set-up a Docker registry
          command: |
              docker run -d -p 5000:5000 --restart=always --name=registry \
                  -v /tmp/docker:/var/lib/registry registry:2
      - run:
          name: Pull existing images
          command: |
              set +e
              docker pull localhost:5000/ubuntu
              success=$?
              set -e
              if [[ "$success" = "0" ]]; then
                  echo "Pulling from local registry"
                  docker tag localhost:5000/ubuntu ubuntu:xenial-20200114
                  docker pull localhost:5000/nitransforms
                  docker tag localhost:5000/nitransforms nitransforms:latest
              else
                  echo "Pulling from Docker Hub"
                  docker pull ubuntu:xenial-20200114
                  docker tag ubuntu:xenial-20200114 localhost:5000/ubuntu
                  docker push localhost:5000/ubuntu
              fi
      - run:
          name: Build Docker image & push to registry
          no_output_timeout: 60m
          command: |
              e=1 && for i in {1..5}; do
                  docker build --rm --cache-from=nitransforms:latest \
                  -t nitransforms:latest \
                  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                  --build-arg VCS_REF=`git rev-parse --short HEAD` \
                  --build-arg VERSION=$( python3 -m setuptools_scm ) . \
                  && e=0 && break || sleep 15
              done && [ "$e" -eq "0" ]
              docker tag nitransforms:latest localhost:5000/nitransforms
              docker push localhost:5000/nitransforms
      - run:
          name: Docker registry garbage collection
          command: |
              docker exec -it registry /bin/registry garbage-collect --delete-untagged \
                  /etc/docker/registry/config.yml
      - save_cache:
          key: build-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/docker
      - run:
          name: Check version packaged in Docker image
          command: |
              THISVERSION=${CIRCLE_TAG:-$(python3 -m setuptools_scm)}
              INSTALLED_VERSION=$(\
                docker run -it --rm --entrypoint=python nitransforms \
                    -c 'import nitransforms as nit; print(nit.__version__, end="")' )
              echo "VERSION: \"${THISVERSION}\""
              echo "INSTALLED: \"${INSTALLED_VERSION}\""
              # test "${INSTALLED_VERSION}" = "${THISVERSION}"
      - run:
          name: Store FreeSurfer license file
          command: |
              mkdir -p /tmp/fslicense
              cd /tmp/fslicense
              echo "cHJpbnRmICJrcnp5c3p0b2YuZ29yZ29sZXdza2lAZ21haWwuY29tXG41MTcyXG4gKkN2dW12RVYzelRmZ1xuRlM1Si8yYzFhZ2c0RVxuIiA+IGxpY2Vuc2UudHh0Cg==" | base64 -d | sh
      - run:
          name: Get codecov
          command: python3 -m pip install codecov
      - run:
          name: Run unit tests
          no_output_timeout: 2h
          command: |
            mkdir -p /tmp/tests/{artifacts,summaries}
            docker run -u $( id -u ) -it --rm \
              -w /src/nitransforms -v $PWD:/src/nitransforms \
              -v /tmp/data/nitransforms-tests:/data -e TEST_DATA_HOME=/data \
              -e COVERAGE_FILE=/tmp/summaries/.pytest.coverage \
              -v /tmp/fslicense/license.txt:/opt/freesurfer/license.txt:ro \
              -v /tmp/tests:/tmp -e TEST_OUTPUT_DIR=/tmp/artifacts \
              nitransforms:latest \
              pytest --junit-xml=/tmp/summaries/pytest.xml \
                     --cov nitransforms --cov-report xml:/tmp/summaries/unittests.xml \
                     nitransforms/
      - run:
          name: Submit unit test coverage
          command: |
            cd /tmp/src/nitransforms
            python3 -m codecov --file /tmp/tests/summaries/unittests.xml \
                --flags unittests -e CIRCLE_JOB
      - run:
          name: Clean up tests directory
          when: on_success
          command: |
            rm -rf /tmp/tests/pytest-of-root
      - store_artifacts:
          path: /tmp/tests/artifacts

      - store_test_results:
          path: /tmp/tests/summaries/

  test_package:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PAT
    working_directory: /tmp/src/nitransforms
    steps:
      - checkout
      - run:
          name: Prepare environment & build
          command: |
            python3 -m venv /tmp/buildenv
            source /tmp/buildenv/bin/activate
            python3 -m pip install "setuptools >= 45.0" build wheel "setuptools_scm[toml] >= 6.2" \
                "pip>=10.0.1" twine docutils
            python3 -m build
            twine check dist/nitransforms*
      - store_artifacts:
          path: /tmp/src/nitransforms/dist
      - persist_to_workspace:
          root: /tmp/src/nitransforms
          paths: dist
      - run:
          name: Install on separate environment and check version [sdist]
          command: |
            python3 -m venv /tmp/install_sdist
            source /tmp/install_sdist/bin/activate
            python3 -m pip install "setuptools >= 45.0" "pip>=10.0.1" "setuptools_scm[toml] >= 6.2"

            THISVERSION=$( python3 -m setuptools_scm )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            python3 -m pip install dist/nitransforms*.tar.gz
            INSTALLED_VERSION=$(python3 -c 'import nitransforms as nit; print(nit.__version__, end="")')
            echo "VERSION: \"${THISVERSION}\""
            echo "INSTALLED: \"${INSTALLED_VERSION}\""
            test "${INSTALLED_VERSION}" = "${THISVERSION}"
      - run:
          name: Install on separate environment and check version [wheel]
          command: |
            python3 -m venv /tmp/install_wheel
            source /tmp/install_wheel/bin/activate
            python3 -m pip install "setuptools >= 45.0" "pip>=10.0.1" "setuptools_scm[toml] >= 6.2"

            THISVERSION=$( python3 -m setuptools_scm )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            python3 -m pip install dist/nitransforms*.whl
            INSTALLED_VERSION=$(python3 -c 'import nitransforms as nit; print(nit.__version__, end="")')
            echo "VERSION: \"${THISVERSION}\""
            echo "INSTALLED: \"${INSTALLED_VERSION}\""
            test "${INSTALLED_VERSION}" = "${THISVERSION}"

  deploy_pypi:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PAT
    working_directory: /tmp/src/nitransforms
    steps:
      - attach_workspace:
          at: /tmp/src/nitransforms
      - run:
          name: Upload to Pypi
          command: |
            python3 -m venv /tmp/upload
            source /tmp/upload/bin/activate
            python3 -m pip install -U twine pip
            python3 -m twine check dist/*
            python3 -m twine upload dist/*

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_pytest:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
            tags:
              only: /.*/

      - test_package:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
            tags:
              only: /.*/

      - deploy_pypi:
          requires:
            - build_pytest
            - test_package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
